image: sashas777/magento-php:7.4-cli
pipelines:
  branches:
    master:
      - step:
          caches:
            - composer
          name: Build
          script:
            - composer config --global http-basic.repo.magento.com $MAGENTO_USER $MAGENTO_PASS
            - composer install --no-suggest --no-ansi --no-interaction
          artifacts:
            - vendor/**
      -   step:
            caches:
              - composer
            services:
              - mysql
              - elasticsearch
            size: 2x
            name: Build | Install | API-Functional tests
            script:
              - rm -rf vendor; rm -rf test-coverage-html;  cd /var/www/magento/;
              - composer config --global http-basic.repo.magento.com $MAGENTO_USER $MAGENTO_PASS
              - composer create-project --repository-url=https://repo.magento.com/  magento/project-community-edition . --no-interaction --no-ansi --no-dev
              - composer config --global repositories.bitbucket.test path $BITBUCKET_CLONE_DIR
              - composer require $(cat $BITBUCKET_CLONE_DIR/composer.json | jq -r '.name') *@dev --update-no-dev
              - bin/magento setup:install --base-url='http://magento2.test/' --admin-firstname='admin' --admin-lastname='admin' --admin-email='admin@magento2.dev' --admin-user='admin' --admin-password='asubdH5Ck6UP58NB' --db-host='127.0.0.1' --db-name='magento2' --db-user='magento2' --db-password='magento2' --cleanup-database --no-interaction --no-ansi
              - bin/magento deploy:mode:set developer
              - cp dev/config/tests/api-functional/config/config-global.php dev/tests/api-functional/config/config-global.php
              - cp dev/config/tests/api-functional/config/install-configmysql.php dev/tests/api-functional/config/install-config-mysql.php
              - cp dev/config/tests/api-functional/phpunit.xml dev/tests/api-functional/phpunit.xml
              - cd dev/tests/api-functional/; ../../../vendor/bin/phpunit --log-junit ./test-reports/junit.xml
            artifacts:
              - /var/www/magento/var/log/debug.log
              - /var/www/magento/var/log/exception.log
              - /var/www/magento/var/log/support_report.log
              - /var/www/magento/var/log/system.log
definitions:
  services:
    mysql:
      image: mariadb:10.2
      environment:
        MYSQL_DATABASE: 'magento2'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'magento2'
        MYSQL_PASSWORD: 'magento2'
    elasticsearch:
      image: sashas777/magento-elasticsearch:7.9.3
      environment:
        ES_NETWORK_HOST: 'localhost'
        ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      ports:
        - "9200:9200"
      memory: 2048
